image: alpine

# Preparation:
# Save $SSH_PRIVATE_KEY first in GitLab CI variables.
variables:
  DRUPAL_PROJECTROOT: "/var/www/drpl.sebastix.dev"
  URL: "https://drpl.sebastix.dev"
  SSH_LOGIN: "ssh -T root@sebastix.dev"
  SSH_USER: "root"
  SSH_HOST: "sebastix.dev"

stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apk add --update openssh )'
  - apk add --update bash
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - apk add rsync
  - rsync --version

deploy_staging:
  when: manual
  stage: deploy
  only:
    - master
  script:
    - ls -la
    - rsync -a --delete -e ssh config $SSH_USER@$SSH_HOST:$DRUPAL_PROJECTROOT
    #- scp -r web/modules/custom $SSH_USER@$SSH_HOST:$DRUPAL_PROJECTROOT/web/modules/custom
    #- scp -r web/themes/custom $SSH_USER@$SSH_HOST:$DRUPAL_PROJECTROOT/web/themes/custom
    - scp composer.json $SSH_USER@$SSH_HOST:$DRUPAL_PROJECTROOT
    - scp composer.lock $SSH_USER@$SSH_HOST:$DRUPAL_PROJECTROOT
    - $SSH_LOGIN "chown -R nginx:nginx $DRUPAL_PROJECTROOT"
    - $SSH_LOGIN "cd $DRUPAL_PROJECTROOT && composer install --optimize-autoloader --no-dev"
    - $SSH_LOGIN "cd $DRUPAL_PROJECTROOT && ls -la"
    # New site install
    #- $SSH_LOGIN "drush si -y"
    # Existing site: updates must be run before configuration is imported
    - $SSH_LOGIN "cd $DRUPAL_PROJECTROOT && drush updatedb -y"
    - $SSH_LOGIN "cd $DRUPAL_PROJECTROOT && drush config-import -y"
    - $SSH_LOGIN "cd $DRUPAL_PROJECTROOT && drush locale:check"
    - $SSH_LOGIN "cd $DRUPAL_PROJECTROOT && drush locale:update"
    - $SSH_LOGIN "cd $DRUPAL_PROJECTROOT && drush core-cron"
    - $SSH_LOGIN "cd $DRUPAL_PROJECTROOT && drush cache-rebuild -y"
    - echo "Deployment ready, check $URL"
