image: alpine

# Preparation:
# Save $SSH_PRIVATE_KEY first in GitLab CI variables.
variables:
  DRUPAL_WEBROOT: "/var/www/drpl.sebastix.dev"
  URL: "https://drpl.sebastix.dev"
  SSH_LOGIN: "ssh -T root@sebastix.dev"
  SSH_USER: "root"
  SSH_HOST: "sebastix.dev"

stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apk add --update openssh )'
  - apk add --update bash
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - vendor/

deploy_staging:
  when: always
  stage: deploy
  only:
    - master
  script:
    - scp composer.json $SSH_USER@$SSH_HOST:$DRUPAL_WEBROOT
    - scp composer.lock $SSH_USER@$SSH_HOST:$DRUPAL_WEBROOT
    - $SSH_LOGIN "cd $DRUPAL_WEBROOT && composer install --optimize-autoloader --no-dev"
    - $SSH_LOGIN "cd $DRUPAL_WEBROOT && ls -la"
    # New site install
    - $SSH_LOGIN "drush si -y"
    # Existing site: updates must be run before configuration is imported
    #- $SSH_LOGIN "cd $DRUPAL_WEBROOT && drush updatedb -y"
    #- $SSH_LOGIN "cd $DRUPAL_WEBROOT && drush config-import -y"
    #- $SSH_LOGIN "cd $DRUPAL_WEBROOT && drush locale:check"
    #- $SSH_LOGIN "cd $DRUPAL_WEBROOT && drush locale:update"
    #- $SSH_LOGIN "cd $DRUPAL_WEBROOT && drush core-cron"
    #- $SSH_LOGIN "cd $DRUPAL_WEBROOT && drush cache-rebuild -y"
    - echo "Deployment ready, check $URL"
