image: alpine

# Preparation:
# Save $SSH_PRIVATE_KEY first in GitLab CI variables.
variables:
  DRUPAL_WEB_ROOT: "/var/www/drpl.sebastix.dev/"
  URL: "https://drpl.sebastix.dev"
  SSH_LOGIN: "ssh -T root@sebastix.dev"

stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apk add --update openssh )'
  - apk add --update bash
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_staging:
  when: always
  stage: deploy
  only:
    - master
  script:
    - $SSH_LOGIN 'cd $DRUPAL_WEB_ROOT && ls -la'
    #- $SSH_LOGIN "cd $DRUPAL_WEB_ROOT && git fetch --tags"
    #- $SSH_LOGIN "cd $DRUPAL_WEB_ROOT && git pull"
    #- $SSH_LOGIN "cd $DRUPAL_WEB_ROOT && composer install --optimize-autoloader --no-dev"
    # New site install
    - $SSH_LOGIN 'drush si -y'

    # Existing site: updates must be run before configuration is imported
    #- $SSH_LOGIN "cd $DRUPAL_WEB_ROOT && drush updatedb -y"
    #- $SSH_LOGIN "cd $DRUPAL_WEB_ROOT && drush config-import -y"
    #- $SSH_LOGIN "cd $DRUPAL_WEB_ROOT && drush locale:check"
    #- $SSH_LOGIN "cd $DRUPAL_WEB_ROOT && drush locale:update"
    #- $SSH_LOGIN "cd $DRUPAL_WEB_ROOT && drush core-cron"
    #- $SSH_LOGIN "cd $DRUPAL_WEB_ROOT && drush cache-rebuild -y"
    - echo 'Deployment ready, check $URL'
