<?php

/**
 * @file
 * Hooks for cchs_notifications module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function cchs_notifications_danse_event_insert(EntityInterface $entity) {
  \Drupal::service('cchs_notifications.web_push')->createNotification();
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
/* function cchs_notifications_danse_event_update(EntityInterface $entity) {
// \Drupal::service('cchs_notifications.web_push')->createNotification();
}*/
